const PDFDocument = require('pdfkit');
const exceljs = require('exceljs');
const Complaint = require('../models/Complaint');

/**
 * @desc    Export complaints to PDF
 * @route   GET /api/exports/pdf
 * @access  Private
 */
const exportPDF = async (req, res) => {
  try {
    let query = {};
    if (req.user.role === 'User') {
      query.user_id = req.user._id;
    } else if (req.user.role === 'Staff') {
      query.assigned_to = req.user._id;
    } else if (req.user.role === 'Department Head') {
      query.department_id = req.user.department_id;
    }

    const complaints = await Complaint.find(query)
      .populate('user_id', 'name email')
      .populate('category_id', 'name')
      .populate('department_id', 'name')
      .populate('assigned_to', 'name email')
      .sort({ createdAt: -1 });

    const doc = new PDFDocument({ margin: 30 });
    
    // Set headers for download
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', 'attachment; filename=complaints_report.pdf');
    
    doc.pipe(res);

    // Title / Header
    doc.fontSize(22).fillColor('#0F766E').text('Complaint & Grievance Report', { align: 'center' });
    doc.fontSize(10).fillColor('#4B5563').text(`Generated on: ${new Date().toLocaleString()}`, { align: 'center' });
    doc.text(`Generated by: ${req.user.name} (${req.user.role})`, { align: 'center' });
    doc.moveDown(2);

    // Table Header
    const yHeader = 120;
    doc.fontSize(10).fillColor('#0F766E');
    doc.text('Ticket ID', 30, yHeader, { width: 80, bold: true });
    doc.text('Title', 110, yHeader, { width: 160, bold: true });
    doc.text('Department', 280, yHeader, { width: 100, bold: true });
    doc.text('Status', 390, yHeader, { width: 60, bold: true });
    doc.text('Priority', 460, yHeader, { width: 60, bold: true });
    doc.text('Created At', 520, yHeader, { width: 60, bold: true });
    
    doc.moveTo(30, yHeader + 15).lineTo(580, yHeader + 15).strokeColor('#14B8A6').stroke();
    
    let y = yHeader + 25;
    doc.fillColor('#1F2937');
    
    complaints.forEach((c) => {
      // Check page boundary
      if (y > 720) {
        doc.addPage();
        y = 40;
        
        // Repeat Header on new pages
        doc.fontSize(10).fillColor('#0F766E');
        doc.text('Ticket ID', 30, y, { width: 80, bold: true });
        doc.text('Title', 110, y, { width: 160, bold: true });
        doc.text('Department', 280, y, { width: 100, bold: true });
        doc.text('Status', 390, y, { width: 60, bold: true });
        doc.text('Priority', 460, y, { width: 60, bold: true });
        doc.text('Created At', 520, y, { width: 60, bold: true });
        doc.moveTo(30, y + 15).lineTo(580, y + 15).strokeColor('#14B8A6').stroke();
        y += 25;
        doc.fillColor('#1F2937');
      }

      const idText = c._id.toString().substring(18).toUpperCase();
      const titleText = c.title.length > 25 ? c.title.substring(0, 22) + '...' : c.title;
      const deptName = c.department_id ? c.department_id.name : 'Unassigned';
      const createdAtText = new Date(c.createdAt).toLocaleDateString();

      doc.text(`#${idText}`, 30, y, { width: 80 });
      doc.text(titleText, 110, y, { width: 160 });
      doc.text(deptName, 280, y, { width: 100 });
      doc.text(c.status, 390, y, { width: 60 });
      doc.text(c.priority, 460, y, { width: 60 });
      doc.text(createdAtText, 520, y, { width: 60 });

      y += 22;
    });

    doc.end();
  } catch (error) {
    console.error('PDF export error:', error);
    res.status(500).json({ message: 'Server error during export', error: error.message });
  }
};

/**
 * @desc    Export complaints to Excel
 * @route   GET /api/exports/excel
 * @access  Private
 */
const exportExcel = async (req, res) => {
  try {
    let query = {};
    if (req.user.role === 'User') {
      query.user_id = req.user._id;
    } else if (req.user.role === 'Staff') {
      query.assigned_to = req.user._id;
    } else if (req.user.role === 'Department Head') {
      query.department_id = req.user.department_id;
    }

    const complaints = await Complaint.find(query)
      .populate('user_id', 'name email')
      .populate('category_id', 'name')
      .populate('department_id', 'name')
      .populate('assigned_to', 'name email')
      .sort({ createdAt: -1 });

    const workbook = new exceljs.Workbook();
    const worksheet = workbook.addWorksheet('Complaints');

    worksheet.columns = [
      { header: 'Ticket ID', key: 'id', width: 25 },
      { header: 'Title', key: 'title', width: 30 },
      { header: 'Description', key: 'description', width: 40 },
      { header: 'Creator Name', key: 'creatorName', width: 20 },
      { header: 'Creator Email', key: 'creatorEmail', width: 25 },
      { header: 'Category', key: 'category', width: 15 },
      { header: 'Department', key: 'department', width: 15 },
      { header: 'Status', key: 'status', width: 12 },
      { header: 'Priority', key: 'priority', width: 12 },
      { header: 'Assigned To', key: 'assignedTo', width: 20 },
      { header: 'Sentiment', key: 'sentiment', width: 12 },
      { header: 'SLA Breach', key: 'slaBreach', width: 12 },
      { header: 'Created At', key: 'createdAt', width: 22 },
      { header: 'Resolved At', key: 'resolvedAt', width: 22 }
    ];

    // Style Header Row
    worksheet.getRow(1).font = { bold: true, color: { argb: 'FFFFFF' } };
    worksheet.getRow(1).fill = {
      type: 'pattern',
      pattern: 'solid',
      fgColor: { argb: '0F766E' }
    };

    complaints.forEach((c) => {
      worksheet.addRow({
        id: c._id.toString(),
        title: c.title,
        description: c.description,
        creatorName: c.user_id ? c.user_id.name : 'N/A',
        creatorEmail: c.user_id ? c.user_id.email : 'N/A',
        category: c.category_id ? c.category_id.name : 'N/A',
        department: c.department_id ? c.department_id.name : 'N/A',
        status: c.status,
        priority: c.priority,
        assignedTo: c.assigned_to ? c.assigned_to.name : 'Unassigned',
        sentiment: c.sentiment,
        slaBreach: c.sla_breach ? 'Yes' : 'No',
        createdAt: c.createdAt.toLocaleString(),
        resolvedAt: c.resolved_at ? c.resolved_at.toLocaleString() : 'N/A'
      });
    });

    res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
    res.setHeader('Content-Disposition', 'attachment; filename=complaints_report.xlsx');

    await workbook.xlsx.write(res);
    res.end();
  } catch (error) {
    console.error('Excel export error:', error);
    res.status(500).json({ message: 'Server error during export', error: error.message });
  }
};

module.exports = {
  exportPDF,
  exportExcel
};
